name: release

on:
  release:
    types: published

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/injectable
    permissions:
      id-token: write
    steps:
      - id: checkout_action
        uses: actions/checkout@master
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
